parameters:
  buildConfig: $(BuildConfig)
  nugetFilter: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
  nugetSource: $(NuGetPrivateSource)
  solution: $(DotNetSolution)

jobs:
  - job: BuildPackPush
    continueOnError: true
    steps:
      - template: setup-dotnet.yml
        parameters:
          previewEnabled: true

      - script: dotnet build ${{ parameters.solution }} -c ${{ parameters.buildConfig }}
        displayName: "Build"

      - script: dotnet pack ${{ parameters.solution }} -c ${{ parameters.buildConfig }} -o $(Build.ArtifactStagingDirectory) --include-symbols --include-source
        displayName: "Pack"

      - task: DotNetCoreCLI@2
        inputs:
          command: "push"
          packagesToPush: ${{ parameters.nugetFilter }}
          nuGetFeedType: "internal"
          publishVstsFeed: ${{ parameters.nugetSource }}
        displayName: "Push"
